config/routes.rb
Serverly::Application.routes.draw do
  resources :servers
  resources :images
  root :to => 'servers#index'
end

app/models/cloud_model_base.rb
class CloudModelBase
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  # declare attributes in subclass with attr_accessor
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  def self.compute
    @compute ||= Fog::Compute.new(
      :provider           => 'Rackspace',
      :rackspace_api_key  => APP_CONFIG[:rackspace_api_key],
      :version => :v2,
      :rackspace_username => APP_CONFIG[:rackspace_username])
  end

end

app/models/flavor.rb
class Flavor < CloudModelBase

  def self.find_by_id(id)
    compute.flavors.get(id)
  end

  def self.all
    compute.flavors
  end

end

app/models/image.rb
class Image < CloudModelBase

  attr_accessor :name,
                :server_id

  validates :name, :presence => true
  validates :server_id, :presence => true


  def self.find_by_id(id)
    compute.images.get(id)
  end

  def self.all
    compute.images
  end

  def self.snapshots
    images = Image.all.partition {|img| img.metadata["image_type"] == "snapshot" }.first
    images.each {|img| img.reload }
  end

  def self.create(params)
    server = Server.find_by_id(params[:server_id])
    image = server.create_image params[:name]
  end

  def self.delete(id)
    compute.images.get(id).destroy
  end

end

app/models/server.rb
class Server < CloudModelBase

  attr_accessor :name, :flavor_id, :image_id

  validates :name, :presence => true
  validates :flavor_id, :presence => true
  validates :image_id, :presence => true

  def self.all
    compute.servers
  end

  def self.find_by_id(id)
    compute.servers.get(id)
  end

  def self.create(params)
    compute.servers.create(:name => params[:name],
                           :flavor_id => params[:flavor_id],
                           :image_id => params[:image_id])
  end

  def self.delete(id)
    compute.servers.get(id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.snapshots
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(params[:image])
    if @image.valid?
      image = Image.create(params[:image])
      flash[:notice] = "Image created"
      redirect_to images_path
    else
      render :action => :new
    end
  end

  def destroy
    @image = Image.find_by_id(params[:id])
    Image.delete(@image.id)
    flash[:notice] = "Image destroyed"
    redirect_to images_path
  end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  def index
    @servers = Server.all
  end

  def new
    @server = Server.new
  end

  def create
    @server = Server.new(params[:server])
    if @server.valid?
      server = Server.create(params[:server])
      flash[:notice] = "Server created"
      redirect_to servers_path
    else
      render :action => :new
    end
  end

  def destroy
    @server = Server.find_by_id(params[:id])
    Server.delete(@server.id)
    flash[:notice] = "Server destroyed"
    redirect_to servers_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def object_options_for_select(object)
    objects = object.to_s.capitalize.constantize.all
    objects_array = objects.map { |object| [object.name, object.id] }
    options_for_select(objects_array)
  end

end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/views/images/_image.html.erb
<li>
<%= link_to "destroy", image_path(image.id), :method => :delete, :confirm => "Are you sure you want to destroy this image?", :class => 'button button-red right' %>
<h2><%= image.name %></h2>
<p class="detail">
  Created at: <%= image.created %> | 
  State: <%= image.state %>
</p>
</li>

app/views/images/index.html.erb
<h1>Image List</h1>
<%= link_to "Create Image", new_image_path, :class => "button button-gray" %>
<ul class="images">
  <%= render :partial => 'image', :collection => @images %>
</ul>

app/views/images/new.html.erb
<%= error_messages_for @image %>

<%= form_for @image do |f| %>
  <div>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :server_id, "Server" %><br>
  <%= f.select :server_id, object_options_for_select(:server) %>
  </div>

  <div>
    <%= f.submit "Create Image" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Serverly</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <div id="navigation">
    <%= link_to "Server List", servers_path, :class => "button button-gray" %>
    <%= link_to "Image List", images_path, :class => "button button-gray" %>
  </div>
  <% flash.each do |key,value| %>
    <p class="flash-<%= key %>"><%= value %></p>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/servers/_server.html.erb
<li>
  <%= link_to "delete", server_path(server.id), :method => :delete, :confirm => "Are you sure you want to delete this server?", :class => "button button-red right"%>
  <h2><%= server.name %></h2>
  <p class="detail">
  Flavor: <%= Flavor.find_by_id(server.flavor_id).name %> | 
  State: <%= server.state %>
  </p>
</li>

app/views/servers/index.html.erb
<h1>Server List</h1>
<%= link_to "Create Server", new_server_path, :class => "button button-gray" %>
<ul class="servers">
  <%= render :partial => 'server', :collection => @servers %>
</ul>

app/views/servers/new.html.erb
<%= error_messages_for @server %>

<%= form_for @server do |f| %>
  <div>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :flavor_id, "Flavor" %><br>
  <%= f.select :flavor_id, object_options_for_select(:flavor) %>
  </div>

  <div>
  <%= f.label :image_id, "Image" %><br>
  <%= f.select :image_id, object_options_for_select(:image) %>
  </div>

  <div>
    <%= f.submit "Create Server" %>
  </div>
<% end %>